// Admin suppliers CRUD — small scope, just answer "who supplies what".
// Purchase orders share the same file since they always live next to
// their supplier and the data volume is tiny.

import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { requireRole } from "../../plugins/auth.js";

function slugify(input: string): string {
  return input
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 200);
}

const supplierCreateSchema = z.object({
  name: z.string().min(1).max(200),
  contactName: z.string().max(200).optional().nullable(),
  contactEmail: z.string().email().max(255).optional().nullable(),
  contactPhone: z.string().max(50).optional().nullable(),
  website: z.string().url().max(500).optional().nullable(),
  country: z.string().length(2).optional(),
  currency: z.string().length(3).optional(),
  paymentTerms: z.string().max(100).optional().nullable(),
  leadTimeDays: z.number().int().nonnegative().optional().nullable(),
  notes: z.string().optional().nullable(),
  isActive: z.boolean().optional(),
});

const supplierUpdateSchema = supplierCreateSchema.partial();

const poCreateSchema = z.object({
  supplierId: z.string().uuid(),
  reference: z.string().min(1).max(50).optional(), // autogenerated if missing
  status: z.enum(["DRAFT", "SENT", "PARTIAL", "RECEIVED", "CANCELLED"]).optional(),
  orderedAt: z.string().datetime().optional().nullable(),
  expectedAt: z.string().datetime().optional().nullable(),
  receivedAt: z.string().datetime().optional().nullable(),
  totalHt: z.number().nonnegative().optional(),
  currency: z.string().length(3).optional(),
  note: z.string().optional().nullable(),
});

const poUpdateSchema = poCreateSchema.partial();

export async function adminSupplierRoutes(app: FastifyInstance) {
  const adminOnly = {
    preHandler: [app.authenticate, requireRole("SUPERADMIN", "ADMIN", "MANAGER")],
  };

  // ─── Suppliers ──────────────────────────────────────────────

  app.get("/admin/suppliers", adminOnly, async (request) => {
    const { q, active } = request.query as { q?: string; active?: string };
    const where: {
      isActive?: boolean;
      OR?: Array<
        | { name: { contains: string; mode: "insensitive" } }
        | { contactEmail: { contains: string; mode: "insensitive" } }
      >;
    } = {};
    if (active === "true") where.isActive = true;
    if (active === "false") where.isActive = false;
    if (q && q.trim()) {
      where.OR = [
        { name: { contains: q.trim(), mode: "insensitive" } },
        { contactEmail: { contains: q.trim(), mode: "insensitive" } },
      ];
    }
    const suppliers = await app.prisma.supplier.findMany({
      where,
      orderBy: { name: "asc" },
      include: { _count: { select: { purchaseOrders: true } } },
    });
    return { success: true, data: suppliers };
  });

  app.post("/admin/suppliers", adminOnly, async (request, reply) => {
    const parsed = supplierCreateSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({
        success: false,
        error: {
          code: "VALIDATION_ERROR",
          message: "Invalid supplier payload",
          details: parsed.error.flatten().fieldErrors,
        },
      });
    }
    const baseSlug = slugify(parsed.data.name);
    const slugTaken = await app.prisma.supplier.findUnique({ where: { slug: baseSlug } });
    const slug = slugTaken ? `${baseSlug}-${Date.now().toString(36)}` : baseSlug;
    const created = await app.prisma.supplier.create({
      data: {
        ...parsed.data,
        slug,
      },
    });
    const userId = (request.user as { userId?: string; id?: string }).userId ?? (request.user as { id?: string }).id;
    app.log.info({ supplierId: created.id, supplierName: parsed.data.name, userId }, "Supplier created");
    return { success: true, data: created };
  });

  app.get("/admin/suppliers/:id", adminOnly, async (request, reply) => {
    const id = (request.params as { id: string }).id;
    const supplier = await app.prisma.supplier.findUnique({
      where: { id },
      include: {
        purchaseOrders: {
          orderBy: { createdAt: "desc" },
          take: 20,
        },
      },
    });
    if (!supplier) {
      return reply.status(404).send({
        success: false,
        error: { code: "NOT_FOUND", message: "Supplier not found" },
      });
    }
    return { success: true, data: supplier };
  });

  app.put("/admin/suppliers/:id", adminOnly, async (request, reply) => {
    const id = (request.params as { id: string }).id;
    const parsed = supplierUpdateSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({
        success: false,
        error: {
          code: "VALIDATION_ERROR",
          message: "Invalid supplier payload",
          details: parsed.error.flatten().fieldErrors,
        },
      });
    }
    const existing = await app.prisma.supplier.findUnique({ where: { id } });
    if (!existing) {
      return reply.status(404).send({
        success: false,
        error: { code: "NOT_FOUND", message: "Supplier not found" },
      });
    }
    const updated = await app.prisma.supplier.update({
      where: { id },
      data: parsed.data,
    });
    const userId = (request.user as { userId?: string; id?: string }).userId ?? (request.user as { id?: string }).id;
    app.log.info({ supplierId: id, userId }, "Supplier updated");
    return { success: true, data: updated };
  });

  app.delete("/admin/suppliers/:id", adminOnly, async (request, reply) => {
    const id = (request.params as { id: string }).id;
    const existing = await app.prisma.supplier.findUnique({
      where: { id },
      include: { _count: { select: { purchaseOrders: true } } },
    });
    if (!existing) {
      return reply.status(404).send({
        success: false,
        error: { code: "NOT_FOUND", message: "Supplier not found" },
      });
    }
    const userId = (request.user as { userId?: string; id?: string }).userId ?? (request.user as { id?: string }).id;
    if (existing._count.purchaseOrders > 0) {
      // Never hard-delete a supplier with POs — they're accounting
      // records. Archive instead.
      const archived = await app.prisma.supplier.update({
        where: { id },
        data: { isActive: false },
      });
      app.log.info({ supplierId: id, userId, archived: true }, "Supplier archived");
      return { success: true, data: archived, archived: true };
    }
    await app.prisma.supplier.delete({ where: { id } });
    app.log.info({ supplierId: id, userId }, "Supplier deleted");
    return { success: true };
  });

  // ─── Purchase orders ────────────────────────────────────────

  app.get("/admin/purchase-orders", adminOnly, async (request) => {
    const { supplierId, status } = request.query as {
      supplierId?: string;
      status?: string;
    };
    const where: { supplierId?: string; status?: string } = {};
    if (supplierId) where.supplierId = supplierId;
    if (status) where.status = status;
    const pos = await app.prisma.purchaseOrder.findMany({
      where,
      orderBy: { createdAt: "desc" },
      take: 100,
      include: {
        supplier: { select: { id: true, name: true, slug: true } },
      },
    });
    return { success: true, data: pos };
  });

  app.post("/admin/purchase-orders", adminOnly, async (request, reply) => {
    const parsed = poCreateSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({
        success: false,
        error: {
          code: "VALIDATION_ERROR",
          message: "Invalid PO payload",
          details: parsed.error.flatten().fieldErrors,
        },
      });
    }
    // Generate sequential reference "PO-YYYY-NNNNN" if none supplied.
    let reference = parsed.data.reference;
    if (!reference) {
      const year = new Date().getFullYear();
      const count = await app.prisma.purchaseOrder.count({
        where: { reference: { startsWith: `PO-${year}-` } },
      });
      reference = `PO-${year}-${String(count + 1).padStart(5, "0")}`;
    }
    const created = await app.prisma.purchaseOrder.create({
      data: {
        supplierId: parsed.data.supplierId,
        reference,
        status: parsed.data.status ?? "DRAFT",
        orderedAt: parsed.data.orderedAt ? new Date(parsed.data.orderedAt) : null,
        expectedAt: parsed.data.expectedAt ? new Date(parsed.data.expectedAt) : null,
        receivedAt: parsed.data.receivedAt ? new Date(parsed.data.receivedAt) : null,
        totalHt: parsed.data.totalHt ?? 0,
        currency: parsed.data.currency ?? "EUR",
        note: parsed.data.note ?? null,
      },
      include: { supplier: { select: { id: true, name: true, slug: true } } },
    });
    const userId = (request.user as { userId?: string; id?: string }).userId ?? (request.user as { id?: string }).id;
    app.log.info({ purchaseOrderId: created.id, reference, supplierId: parsed.data.supplierId, userId }, "Purchase order created");
    return { success: true, data: created };
  });

  app.put("/admin/purchase-orders/:id", adminOnly, async (request, reply) => {
    const id = (request.params as { id: string }).id;
    const parsed = poUpdateSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({
        success: false,
        error: {
          code: "VALIDATION_ERROR",
          message: "Invalid PO payload",
          details: parsed.error.flatten().fieldErrors,
        },
      });
    }
    const existing = await app.prisma.purchaseOrder.findUnique({ where: { id } });
    if (!existing) {
      return reply.status(404).send({
        success: false,
        error: { code: "NOT_FOUND", message: "PO not found" },
      });
    }
    const updated = await app.prisma.purchaseOrder.update({
      where: { id },
      data: {
        ...(parsed.data.supplierId !== undefined && { supplierId: parsed.data.supplierId }),
        ...(parsed.data.status !== undefined && { status: parsed.data.status }),
        ...(parsed.data.orderedAt !== undefined && {
          orderedAt: parsed.data.orderedAt ? new Date(parsed.data.orderedAt) : null,
        }),
        ...(parsed.data.expectedAt !== undefined && {
          expectedAt: parsed.data.expectedAt ? new Date(parsed.data.expectedAt) : null,
        }),
        ...(parsed.data.receivedAt !== undefined && {
          receivedAt: parsed.data.receivedAt ? new Date(parsed.data.receivedAt) : null,
        }),
        ...(parsed.data.totalHt !== undefined && { totalHt: parsed.data.totalHt }),
        ...(parsed.data.note !== undefined && { note: parsed.data.note ?? null }),
      },
      include: { supplier: { select: { id: true, name: true, slug: true } } },
    });
    const userId = (request.user as { userId?: string; id?: string }).userId ?? (request.user as { id?: string }).id;
    app.log.info({ purchaseOrderId: id, reference: existing.reference, userId }, "Purchase order updated");
    return { success: true, data: updated };
  });

  app.delete("/admin/purchase-orders/:id", adminOnly, async (request, reply) => {
    const id = (request.params as { id: string }).id;
    const existing = await app.prisma.purchaseOrder.findUnique({ where: { id } });
    if (!existing) {
      return reply.status(404).send({
        success: false,
        error: { code: "NOT_FOUND", message: "PO not found" },
      });
    }
    const userId = (request.user as { userId?: string; id?: string }).userId ?? (request.user as { id?: string }).id;
    // Only DRAFT POs can be hard-deleted; past that they become
    // accounting history.
    if (existing.status !== "DRAFT") {
      const cancelled = await app.prisma.purchaseOrder.update({
        where: { id },
        data: { status: "CANCELLED" },
      });
      app.log.info({ purchaseOrderId: id, reference: existing.reference, userId, cancelled: true }, "Purchase order cancelled");
      return { success: true, data: cancelled, cancelled: true };
    }
    await app.prisma.purchaseOrder.delete({ where: { id } });
    app.log.info({ purchaseOrderId: id, reference: existing.reference, userId }, "Purchase order deleted");
    return { success: true };
  });
}
