// Admin suppliers CRUD — small scope, just answer "who supplies what".
// Purchase orders share the same file since they always live next to
// their supplier and the data volume is tiny.

import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { requireRole } from "../../plugins/auth.js";
import { notifyBackInStock } from "../../lib/back-in-stock.js";

function slugify(input: string): string {
  return input
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 200);
}

const supplierCreateSchema = z.object({
  name: z.string().min(1).max(200),
  contactName: z.string().max(200).optional().nullable(),
  contactEmail: z.string().email().max(255).optional().nullable(),
  contactPhone: z.string().max(50).optional().nullable(),
  website: z.string().url().max(500).optional().nullable(),
  country: z.string().length(2).optional(),
  currency: z.string().length(3).optional(),
  paymentTerms: z.string().max(100).optional().nullable(),
  leadTimeDays: z.number().int().nonnegative().optional().nullable(),
  notes: z.string().optional().nullable(),
  isActive: z.boolean().optional(),
});

const supplierUpdateSchema = supplierCreateSchema.partial();

const poCreateSchema = z.object({
  supplierId: z.string().uuid(),
  reference: z.string().min(1).max(50).optional(), // autogenerated if missing
  status: z.enum(["DRAFT", "SENT", "PARTIAL", "RECEIVED", "CANCELLED"]).optional(),
  orderedAt: z.string().datetime().optional().nullable(),
  expectedAt: z.string().datetime().optional().nullable(),
  receivedAt: z.string().datetime().optional().nullable(),
  totalHt: z.number().nonnegative().optional(),
  currency: z.string().length(3).optional(),
  note: z.string().optional().nullable(),
  items: z
    .array(
      z.object({
        variantId: z.string().uuid(),
        quantityOrdered: z.number().int().positive(),
        unitCostHt: z.number().nonnegative().optional(),
      }),
    )
    .optional(),
});

const poUpdateSchema = poCreateSchema.omit({ items: true }).partial();

const poItemsSchema = z.object({
  items: z
    .array(
      z.object({
        variantId: z.string().uuid(),
        quantityOrdered: z.number().int().positive(),
        unitCostHt: z.number().nonnegative().optional(),
      }),
    )
    .min(1),
});

const poReceiveSchema = z.object({
  lines: z
    .array(
      z.object({
        variantId: z.string().uuid(),
        quantityReceived: z.number().int().positive(),
      }),
    )
    .min(1),
  note: z.string().max(500).optional(),
});

export async function adminSupplierRoutes(app: FastifyInstance) {
  const adminOnly = {
    preHandler: [app.authenticate, requireRole("SUPERADMIN", "ADMIN", "MANAGER")],
  };

  // ─── Suppliers ──────────────────────────────────────────────

  app.get("/admin/suppliers", adminOnly, async (request) => {
    const { q, active } = request.query as { q?: string; active?: string };
    const where: {
      isActive?: boolean;
      OR?: Array<
        | { name: { contains: string; mode: "insensitive" } }
        | { contactEmail: { contains: string; mode: "insensitive" } }
      >;
    } = {};
    if (active === "true") where.isActive = true;
    if (active === "false") where.isActive = false;
    if (q && q.trim()) {
      where.OR = [
        { name: { contains: q.trim(), mode: "insensitive" } },
        { contactEmail: { contains: q.trim(), mode: "insensitive" } },
      ];
    }
    const suppliers = await app.prisma.supplier.findMany({
      where,
      orderBy: { name: "asc" },
      include: { _count: { select: { purchaseOrders: true } } },
    });
    return { success: true, data: suppliers };
  });

  app.post("/admin/suppliers", adminOnly, async (request, reply) => {
    const parsed = supplierCreateSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({
        success: false,
        error: {
          code: "VALIDATION_ERROR",
          message: "Invalid supplier payload",
          details: parsed.error.flatten().fieldErrors,
        },
      });
    }
    const baseSlug = slugify(parsed.data.name);
    const slugTaken = await app.prisma.supplier.findUnique({ where: { slug: baseSlug } });
    const slug = slugTaken ? `${baseSlug}-${Date.now().toString(36)}` : baseSlug;
    const created = await app.prisma.supplier.create({
      data: {
        ...parsed.data,
        slug,
      },
    });
    const userId = (request.user as { userId?: string; id?: string }).userId ?? (request.user as { id?: string }).id;
    app.log.info({ supplierId: created.id, supplierName: parsed.data.name, userId }, "Supplier created");
    return { success: true, data: created };
  });

  app.get("/admin/suppliers/:id", adminOnly, async (request, reply) => {
    const id = (request.params as { id: string }).id;
    const supplier = await app.prisma.supplier.findUnique({
      where: { id },
      include: {
        purchaseOrders: {
          orderBy: { createdAt: "desc" },
          take: 20,
        },
      },
    });
    if (!supplier) {
      return reply.status(404).send({
        success: false,
        error: { code: "NOT_FOUND", message: "Supplier not found" },
      });
    }
    return { success: true, data: supplier };
  });

  app.put("/admin/suppliers/:id", adminOnly, async (request, reply) => {
    const id = (request.params as { id: string }).id;
    const parsed = supplierUpdateSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({
        success: false,
        error: {
          code: "VALIDATION_ERROR",
          message: "Invalid supplier payload",
          details: parsed.error.flatten().fieldErrors,
        },
      });
    }
    const existing = await app.prisma.supplier.findUnique({ where: { id } });
    if (!existing) {
      return reply.status(404).send({
        success: false,
        error: { code: "NOT_FOUND", message: "Supplier not found" },
      });
    }
    const updated = await app.prisma.supplier.update({
      where: { id },
      data: parsed.data,
    });
    const userId = (request.user as { userId?: string; id?: string }).userId ?? (request.user as { id?: string }).id;
    app.log.info({ supplierId: id, userId }, "Supplier updated");
    return { success: true, data: updated };
  });

  app.delete("/admin/suppliers/:id", adminOnly, async (request, reply) => {
    const id = (request.params as { id: string }).id;
    const existing = await app.prisma.supplier.findUnique({
      where: { id },
      include: { _count: { select: { purchaseOrders: true } } },
    });
    if (!existing) {
      return reply.status(404).send({
        success: false,
        error: { code: "NOT_FOUND", message: "Supplier not found" },
      });
    }
    const userId = (request.user as { userId?: string; id?: string }).userId ?? (request.user as { id?: string }).id;
    if (existing._count.purchaseOrders > 0) {
      // Never hard-delete a supplier with POs — they're accounting
      // records. Archive instead.
      const archived = await app.prisma.supplier.update({
        where: { id },
        data: { isActive: false },
      });
      app.log.info({ supplierId: id, userId, archived: true }, "Supplier archived");
      return { success: true, data: archived, archived: true };
    }
    await app.prisma.supplier.delete({ where: { id } });
    app.log.info({ supplierId: id, userId }, "Supplier deleted");
    return { success: true };
  });

  // ─── Purchase orders ────────────────────────────────────────

  app.get("/admin/purchase-orders", adminOnly, async (request) => {
    const { supplierId, status } = request.query as {
      supplierId?: string;
      status?: string;
    };
    const where: { supplierId?: string; status?: string } = {};
    if (supplierId) where.supplierId = supplierId;
    if (status) where.status = status;
    const pos = await app.prisma.purchaseOrder.findMany({
      where,
      orderBy: { createdAt: "desc" },
      take: 100,
      include: {
        supplier: { select: { id: true, name: true, slug: true } },
        items: { include: { variant: { select: { sku: true, name: true, product: { select: { name: true } } } } } },
      },
    });
    return { success: true, data: pos };
  });

  app.post("/admin/purchase-orders", adminOnly, async (request, reply) => {
    const parsed = poCreateSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({
        success: false,
        error: {
          code: "VALIDATION_ERROR",
          message: "Invalid PO payload",
          details: parsed.error.flatten().fieldErrors,
        },
      });
    }
    // Generate sequential reference "PO-YYYY-NNNNN" if none supplied.
    let reference = parsed.data.reference;
    if (!reference) {
      const year = new Date().getFullYear();
      const count = await app.prisma.purchaseOrder.count({
        where: { reference: { startsWith: `PO-${year}-` } },
      });
      reference = `PO-${year}-${String(count + 1).padStart(5, "0")}`;
    }
    const created = await app.prisma.purchaseOrder.create({
      data: {
        supplierId: parsed.data.supplierId,
        reference,
        status: parsed.data.status ?? "DRAFT",
        orderedAt: parsed.data.orderedAt ? new Date(parsed.data.orderedAt) : null,
        expectedAt: parsed.data.expectedAt ? new Date(parsed.data.expectedAt) : null,
        receivedAt: parsed.data.receivedAt ? new Date(parsed.data.receivedAt) : null,
        totalHt:
          parsed.data.totalHt ??
          (parsed.data.items ?? []).reduce((sum, i) => sum + (i.unitCostHt ?? 0) * i.quantityOrdered, 0),
        currency: parsed.data.currency ?? "EUR",
        note: parsed.data.note ?? null,
        items: parsed.data.items
          ? { create: parsed.data.items.map((i) => ({ variantId: i.variantId, quantityOrdered: i.quantityOrdered, unitCostHt: i.unitCostHt ?? 0 })) }
          : undefined,
      },
      include: {
        supplier: { select: { id: true, name: true, slug: true } },
        items: { include: { variant: { select: { sku: true, name: true, product: { select: { name: true } } } } } },
      },
    });
    const userId = (request.user as { userId?: string; id?: string }).userId ?? (request.user as { id?: string }).id;
    app.log.info({ purchaseOrderId: created.id, reference, supplierId: parsed.data.supplierId, userId }, "Purchase order created");
    return { success: true, data: created };
  });

  app.put("/admin/purchase-orders/:id", adminOnly, async (request, reply) => {
    const id = (request.params as { id: string }).id;
    const parsed = poUpdateSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({
        success: false,
        error: {
          code: "VALIDATION_ERROR",
          message: "Invalid PO payload",
          details: parsed.error.flatten().fieldErrors,
        },
      });
    }
    const existing = await app.prisma.purchaseOrder.findUnique({ where: { id } });
    if (!existing) {
      return reply.status(404).send({
        success: false,
        error: { code: "NOT_FOUND", message: "PO not found" },
      });
    }
    const updated = await app.prisma.purchaseOrder.update({
      where: { id },
      data: {
        ...(parsed.data.supplierId !== undefined && { supplierId: parsed.data.supplierId }),
        ...(parsed.data.status !== undefined && { status: parsed.data.status }),
        ...(parsed.data.orderedAt !== undefined && {
          orderedAt: parsed.data.orderedAt ? new Date(parsed.data.orderedAt) : null,
        }),
        ...(parsed.data.expectedAt !== undefined && {
          expectedAt: parsed.data.expectedAt ? new Date(parsed.data.expectedAt) : null,
        }),
        ...(parsed.data.receivedAt !== undefined && {
          receivedAt: parsed.data.receivedAt ? new Date(parsed.data.receivedAt) : null,
        }),
        ...(parsed.data.totalHt !== undefined && { totalHt: parsed.data.totalHt }),
        ...(parsed.data.note !== undefined && { note: parsed.data.note ?? null }),
      },
      include: { supplier: { select: { id: true, name: true, slug: true } } },
    });
    const userId = (request.user as { userId?: string; id?: string }).userId ?? (request.user as { id?: string }).id;
    app.log.info({ purchaseOrderId: id, reference: existing.reference, userId }, "Purchase order updated");
    return { success: true, data: updated };
  });

  app.delete("/admin/purchase-orders/:id", adminOnly, async (request, reply) => {
    const id = (request.params as { id: string }).id;
    const existing = await app.prisma.purchaseOrder.findUnique({ where: { id } });
    if (!existing) {
      return reply.status(404).send({
        success: false,
        error: { code: "NOT_FOUND", message: "PO not found" },
      });
    }
    const userId = (request.user as { userId?: string; id?: string }).userId ?? (request.user as { id?: string }).id;
    // Only DRAFT POs can be hard-deleted; past that they become
    // accounting history.
    if (existing.status !== "DRAFT") {
      const cancelled = await app.prisma.purchaseOrder.update({
        where: { id },
        data: { status: "CANCELLED" },
      });
      app.log.info({ purchaseOrderId: id, reference: existing.reference, userId, cancelled: true }, "Purchase order cancelled");
      return { success: true, data: cancelled, cancelled: true };
    }
    await app.prisma.purchaseOrder.delete({ where: { id } });
    app.log.info({ purchaseOrderId: id, reference: existing.reference, userId }, "Purchase order deleted");
    return { success: true };
  });

  // PUT /admin/purchase-orders/:id/items — replace the lines of a DRAFT/SENT order
  app.put("/admin/purchase-orders/:id/items", adminOnly, async (request, reply) => {
    const { id } = request.params as { id: string };
    const parsed = poItemsSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({
        success: false,
        error: { code: "VALIDATION_ERROR", message: "Invalid PO items", details: parsed.error.flatten().fieldErrors },
      });
    }
    const po = await app.prisma.purchaseOrder.findUnique({ where: { id }, select: { status: true } });
    if (!po) return reply.status(404).send({ success: false, error: { code: "NOT_FOUND", message: "Bon de commande introuvable" } });
    if (!["DRAFT", "SENT"].includes(po.status)) {
      return reply.status(409).send({
        success: false,
        error: { code: "PO_LOCKED", message: "Les lignes ne sont modifiables qu'avant réception" },
      });
    }
    const totalHt = parsed.data.items.reduce((sum, i) => sum + (i.unitCostHt ?? 0) * i.quantityOrdered, 0);
    const updated = await app.prisma.$transaction(async (tx) => {
      await tx.purchaseOrderItem.deleteMany({ where: { purchaseOrderId: id } });
      return tx.purchaseOrder.update({
        where: { id },
        data: {
          totalHt,
          items: { create: parsed.data.items.map((i) => ({ variantId: i.variantId, quantityOrdered: i.quantityOrdered, unitCostHt: i.unitCostHt ?? 0 })) },
        },
        include: { items: { include: { variant: { select: { sku: true, name: true, product: { select: { name: true } } } } } } },
      });
    });
    return { success: true, data: updated };
  });

  // POST /admin/purchase-orders/:id/receive — réception (totale ou partielle)
  // Each line increments the variant stock and writes an IN_PURCHASE movement;
  // the PO becomes PARTIAL or RECEIVED from the sum of its lines.
  app.post("/admin/purchase-orders/:id/receive", adminOnly, async (request, reply) => {
    const { id } = request.params as { id: string };
    const parsed = poReceiveSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({
        success: false,
        error: { code: "VALIDATION_ERROR", message: "Invalid receipt", details: parsed.error.flatten().fieldErrors },
      });
    }
    const user = request.user as { userId?: string; id?: string };
    const performedBy = user.userId ?? user.id ?? null;

    try {
      const result = await app.prisma.$transaction(async (tx) => {
        const po = await tx.purchaseOrder.findUnique({ where: { id }, include: { items: true } });
        if (!po) throw Object.assign(new Error("Bon de commande introuvable"), { statusCode: 404, code: "NOT_FOUND" });
        if (po.status === "CANCELLED" || po.status === "RECEIVED") {
          throw Object.assign(new Error(`Bon de commande ${po.status}`), { statusCode: 409, code: "PO_CLOSED" });
        }
        const byVariant = new Map(po.items.map((i) => [i.variantId, i]));
        const received: Array<{ variantId: string; quantity: number; stockAfter: number; overReceived: boolean }> = [];

        for (const line of parsed.data.lines) {
          const item = byVariant.get(line.variantId);
          if (!item) {
            throw Object.assign(new Error(`Variante ${line.variantId} absente du bon de commande`), {
              statusCode: 400,
              code: "LINE_NOT_ON_PO",
            });
          }
          const variant = await tx.productVariant.update({
            where: { id: line.variantId },
            data: { stockQuantity: { increment: line.quantityReceived } },
            select: { stockQuantity: true },
          });
          await tx.purchaseOrderItem.update({
            where: { id: item.id },
            data: { quantityReceived: { increment: line.quantityReceived } },
          });
          await tx.stockMovement.create({
            data: {
              variantId: line.variantId,
              type: "IN_PURCHASE",
              quantity: line.quantityReceived,
              reason: parsed.data.note ?? `Réception ${po.reference}`,
              referenceId: po.id,
              referenceType: "PURCHASE_ORDER",
              performedBy,
              stockBefore: variant.stockQuantity - line.quantityReceived,
              stockAfter: variant.stockQuantity,
            },
          });
          received.push({
            variantId: line.variantId,
            quantity: line.quantityReceived,
            stockAfter: variant.stockQuantity,
            overReceived: item.quantityReceived + line.quantityReceived > item.quantityOrdered,
          });
        }

        const items = await tx.purchaseOrderItem.findMany({ where: { purchaseOrderId: id } });
        const complete = items.every((i) => i.quantityReceived >= i.quantityOrdered);
        const updated = await tx.purchaseOrder.update({
          where: { id },
          data: { status: complete ? "RECEIVED" : "PARTIAL", receivedAt: complete ? new Date() : po.receivedAt },
          include: { items: { include: { variant: { select: { sku: true, name: true, product: { select: { name: true } } } } } } },
        });
        return { purchaseOrder: updated, received };
      });
      app.log.info({ purchaseOrderId: id, lines: result.received.length, performedBy }, "Purchase order received");
      // Customers waiting for these products (back-in-stock alerts) — outside the transaction.
      for (const line of result.received) {
        if (line.stockAfter > 0 && line.stockAfter - line.quantity <= 0) notifyBackInStock(app, line.variantId);
      }
      return { success: true, data: result };
    } catch (err) {
      const e = err as { statusCode?: number; code?: string; message?: string };
      if (e.statusCode && e.statusCode < 500) {
        return reply.status(e.statusCode).send({ success: false, error: { code: e.code ?? "ERROR", message: e.message ?? "" } });
      }
      throw err;
    }
  });
}
